[package]
name = "conflation"
version = "0.1.0"
edition = "2021"

[dependencies]
linked-hash-map = "0.5.4"
parking_lot = "0.12.1"

[dev-dependencies]
criterion = "0.3.5"

[[bench]]
name = "sync_compare"
harness = false

[[bench]]
name = "sync_stress"
harness = false